import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  elevation,
  lightTheme,
  motionTokens,
  radius,
  space,
  themes,
  tokens,
  typography,
} from "./tokens";

const HEADER =
  "/* AUTO-GENERATED by @awesome-ds/tokens — do not edit by hand. Source: packages/tokens/src/tokens.ts */\n";

function entriesToCss(vars: Record<string, string>, indent = "  "): string {
  return Object.entries(vars)
    .map(([k, v]) => `${indent}--${k}: ${v};`)
    .join("\n");
}

function buildTokensCss(): string {
  const root = {
    ...Object.fromEntries(
      Object.entries(lightTheme).map(([k, v]) => [k, v]),
    ),
    ...space,
    ...radius,
    ...typography,
    ...elevation,
    ...Object.fromEntries(
      Object.entries(motionTokens).filter(([k]) => !k.includes("reduced")),
    ),
  };

  const dark = themes.dark;
  const hc = themes["high-contrast"];

  return `${HEADER}:root {
  color-scheme: light dark;
${entriesToCss(root)}
}

[data-theme="dark"],
.dark {
  color-scheme: dark;
${entriesToCss(dark)}
}

[data-theme="high-contrast"],
.high-contrast {
${entriesToCss(hc)}
}

@media (prefers-reduced-motion: reduce) {
  :root {
    --dur-fast: ${motionTokens["dur-fast-reduced"]};
    --dur-base: ${motionTokens["dur-base-reduced"]};
    --dur-slow: ${motionTokens["dur-slow-reduced"]};
  }
}
`;
}

function buildTailwindTheme(): string {
  const colorMap = Object.keys(lightTheme)
    .map((k) => `  --color-ads-${k.replace(/^color-/, "")}: var(--${k});`)
    .join("\n");
  const spaceMap = Object.keys(space)
    .map((k) => `  --${k.replace("space-", "spacing-")}: var(--${k});`)
    .join("\n");

  return `${HEADER}@theme {
${colorMap}
${spaceMap}
  --font-ads-display: var(--font-display);
  --font-ads-body: var(--font-body);
  --font-ads-mono: var(--font-mono);
  --radius-ads-sm: var(--radius-sm);
  --radius-ads-md: var(--radius-md);
  --radius-ads-lg: var(--radius-lg);
  --radius-ads-xl: var(--radius-xl);
  --radius-ads-2xl: var(--radius-2xl);
  --ease-ads-out: var(--ease-out);
  --ease-ads-in-out: var(--ease-in-out);
  --animate-duration-fast: var(--dur-fast);
  --animate-duration-base: var(--dur-base);
  --animate-duration-slow: var(--dur-slow);
}
`;
}

export async function generate(outDir: string): Promise<void> {
  await mkdir(outDir, { recursive: true });
  await writeFile(path.join(outDir, "tokens.css"), buildTokensCss(), "utf8");
  await writeFile(
    path.join(outDir, "tailwind-theme.css"),
    buildTailwindTheme(),
    "utf8",
  );
  await writeFile(
    path.join(outDir, "tokens.json"),
    `${JSON.stringify(tokens, null, 2)}\n`,
    "utf8",
  );
}

const isMain = process.argv[1] === fileURLToPath(import.meta.url);
if (isMain) {
  const dist = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../dist");
  await generate(dist);
  console.log(`Wrote tokens to ${dist}`);
}
