export type ComponentCatalogItem = {
  slug: string;
  name: string;
  family: "primitives" | "forms" | "overlay" | "navigation" | "status" | "layout";
  description: string;
  ruleIds: string[];
  states: string[];
  importName: string;
  example: string;
};

export const componentCatalog: ComponentCatalogItem[] = [
  {
    slug: "button",
    name: "Button",
    family: "primitives",
    description: "Primary actions with loading and disabled states.",
    ruleIds: ["rule.a11y.wcag-aa", "rule.components.state-matrix"],
    states: ["idle", "hover", "focus", "active", "disabled", "loading"],
    importName: "Button",
    example: `import { Button } from "@awesome-ds/react";\n\n<Button loading>Save</Button>`,
  },
  {
    slug: "icon-button",
    name: "IconButton",
    family: "primitives",
    description: "Icon-only control requiring an accessible name.",
    ruleIds: ["rule.a11y.wcag-aa"],
    states: ["idle", "disabled", "loading"],
    importName: "IconButton",
    example: `<IconButton label="Close">×</IconButton>`,
  },
  {
    slug: "link",
    name: "Link",
    family: "primitives",
    description: "Semantic navigation link styled with accent.",
    ruleIds: ["rule.a11y.wcag-aa", "rule.interaction.interface-quality"],
    states: ["idle", "hover", "focus", "visited"],
    importName: "Link",
    example: `<Link href="/references">Atlas</Link>`,
  },
  {
    slug: "badge",
    name: "Badge",
    family: "primitives",
    description: "Compact status or category label.",
    ruleIds: ["rule.foundations.semantic-tokens"],
    states: ["idle"],
    importName: "Badge",
    example: `<Badge tone="accent">New</Badge>`,
  },
  {
    slug: "input",
    name: "Input",
    family: "forms",
    description: "Labeled text field with hint and error association.",
    ruleIds: ["rule.a11y.wcag-aa", "rule.components.state-matrix"],
    states: ["idle", "focus", "disabled", "error"],
    importName: "Input",
    example: `<Input id="email" label="Email" error="Required" />`,
  },
  {
    slug: "textarea",
    name: "Textarea",
    family: "forms",
    description: "Multi-line labeled field.",
    ruleIds: ["rule.a11y.wcag-aa"],
    states: ["idle", "focus", "disabled", "error"],
    importName: "Textarea",
    example: `<Textarea id="bio" label="Bio" />`,
  },
  {
    slug: "checkbox",
    name: "Checkbox",
    family: "forms",
    description: "Binary choice with label.",
    ruleIds: ["rule.a11y.wcag-aa"],
    states: ["unchecked", "checked", "disabled"],
    importName: "Checkbox",
    example: `<Checkbox id="tos" label="Accept terms" />`,
  },
  {
    slug: "switch",
    name: "Switch",
    family: "forms",
    description: "Immediate on/off control with switch role.",
    ruleIds: ["rule.a11y.wcag-aa"],
    states: ["off", "on", "disabled"],
    importName: "Switch",
    example: `<Switch id="dark" label="Dark mode" />`,
  },
  {
    slug: "radio-group",
    name: "RadioGroup",
    family: "forms",
    description: "Single selection within a named group.",
    ruleIds: ["rule.a11y.wcag-aa"],
    states: ["selected", "unselected"],
    importName: "RadioGroup",
    example: `<RadioGroup legend="Plan" name="plan" options={[{value:'free',label:'Free'}]} />`,
  },
  {
    slug: "select",
    name: "Select",
    family: "forms",
    description: "Native select with label and error.",
    ruleIds: ["rule.a11y.wcag-aa"],
    states: ["idle", "disabled", "error"],
    importName: "Select",
    example: `<Select id="role" label="Role"><option>Admin</option></Select>`,
  },
  {
    slug: "dialog",
    name: "Dialog",
    family: "overlay",
    description: "Modal dialog with Escape dismiss and labelled title.",
    ruleIds: ["rule.a11y.wcag-aa", "rule.components.state-matrix"],
    states: ["open", "closed"],
    importName: "Dialog",
    example: `<Dialog open title="Confirm" onClose={() => {}}>Body</Dialog>`,
  },
  {
    slug: "alert-dialog",
    name: "AlertDialog",
    family: "overlay",
    description: "Destructive confirmation dialog variant.",
    ruleIds: ["rule.a11y.wcag-aa"],
    states: ["open", "closed"],
    importName: "AlertDialog",
    example: `<AlertDialog open title="Delete" onClose={() => {}}>Sure?</AlertDialog>`,
  },
  {
    slug: "popover",
    name: "Popover",
    family: "overlay",
    description: "Lightweight non-modal disclosure.",
    ruleIds: ["rule.a11y.wcag-aa"],
    states: ["open", "closed"],
    importName: "Popover",
    example: `<Popover label="More">Details</Popover>`,
  },
  {
    slug: "tooltip",
    name: "Tooltip",
    family: "overlay",
    description: "Supplementary description for a control.",
    ruleIds: ["rule.a11y.wcag-aa"],
    states: ["idle"],
    importName: "Tooltip",
    example: `<Tooltip label="Save">?</Tooltip>`,
  },
  {
    slug: "dropdown-menu",
    name: "DropdownMenu",
    family: "overlay",
    description: "Action menu with menuitem roles.",
    ruleIds: ["rule.a11y.wcag-aa"],
    states: ["open", "closed"],
    importName: "DropdownMenu",
    example: `<DropdownMenu label="Actions" items={[{id:'a',label:'Edit'}]} />`,
  },
  {
    slug: "tabs",
    name: "Tabs",
    family: "navigation",
    description: "Tablist / tab / tabpanel pattern.",
    ruleIds: ["rule.a11y.wcag-aa", "rule.components.state-matrix"],
    states: ["selected"],
    importName: "Tabs",
    example: `<Tabs items={[{value:'a',label:'A',content:'A'}]} />`,
  },
  {
    slug: "accordion",
    name: "Accordion",
    family: "navigation",
    description: "Native details/summary disclosure list.",
    ruleIds: ["rule.a11y.wcag-aa", "rule.motion.purpose-first"],
    states: ["expanded", "collapsed"],
    importName: "Accordion",
    example: `<Accordion items={[{id:'1',title:'Q',content:'A'}]} />`,
  },
  {
    slug: "breadcrumb",
    name: "Breadcrumb",
    family: "navigation",
    description: "Hierarchical location trail.",
    ruleIds: ["rule.a11y.wcag-aa"],
    states: ["current"],
    importName: "Breadcrumb",
    example: `<Breadcrumb items={[{label:'Home',href:'/'},{label:'Here'}]} />`,
  },
  {
    slug: "pagination",
    name: "Pagination",
    family: "navigation",
    description: "Paged navigation with live page announcement.",
    ruleIds: ["rule.interaction.url-state"],
    states: ["first", "middle", "last"],
    importName: "Pagination",
    example: `<Pagination page={2} pageCount={5} onChange={() => {}} />`,
  },
  {
    slug: "card",
    name: "Card",
    family: "status",
    description: "Surface container for grouped content.",
    ruleIds: ["rule.foundations.semantic-tokens"],
    states: ["idle"],
    importName: "Card",
    example: `<Card title="Title">Body</Card>`,
  },
  {
    slug: "callout",
    name: "Callout",
    family: "status",
    description: "Inline emphasis for tips or warnings.",
    ruleIds: ["rule.brand.content-design"],
    states: ["idle"],
    importName: "Callout",
    example: `<Callout title="Note">Details</Callout>`,
  },
  {
    slug: "skeleton",
    name: "Skeleton",
    family: "status",
    description: "Loading placeholder matching content geometry.",
    ruleIds: ["rule.interaction.product-quality"],
    states: ["loading"],
    importName: "Skeleton",
    example: `<Skeleton height="2rem" />`,
  },
  {
    slug: "spinner",
    name: "Spinner",
    family: "status",
    description: "Indeterminate progress indicator.",
    ruleIds: ["rule.a11y.wcag-aa"],
    states: ["loading"],
    importName: "Spinner",
    example: `<Spinner label="Loading" />`,
  },
  {
    slug: "progress",
    name: "Progress",
    family: "status",
    description: "Determinate progressbar.",
    ruleIds: ["rule.a11y.wcag-aa"],
    states: ["0", "partial", "100"],
    importName: "Progress",
    example: `<Progress value={40} label="Upload" />`,
  },
  {
    slug: "toast",
    name: "Toast",
    family: "status",
    description: "Transient status message.",
    ruleIds: ["rule.interaction.product-quality"],
    states: ["visible"],
    importName: "Toast",
    example: `<Toast>Saved</Toast>`,
  },
  {
    slug: "empty-state",
    name: "EmptyState",
    family: "status",
    description: "Empty collection with next action.",
    ruleIds: ["rule.interaction.product-quality"],
    states: ["empty"],
    importName: "EmptyState",
    example: `<EmptyState title="None" description="Add one" actionLabel="Create" />`,
  },
  {
    slug: "error-state",
    name: "ErrorState",
    family: "status",
    description: "Failure recovery surface.",
    ruleIds: ["rule.interaction.product-quality"],
    states: ["error"],
    importName: "ErrorState",
    example: `<ErrorState title="Failed" description="Retry" actionLabel="Retry" />`,
  },
  {
    slug: "stack",
    name: "Stack",
    family: "layout",
    description: "Vertical flex stack with gap tokens.",
    ruleIds: ["rule.foundations.semantic-tokens"],
    states: ["idle"],
    importName: "Stack",
    example: `<Stack gap={4}>…</Stack>`,
  },
  {
    slug: "cluster",
    name: "Cluster",
    family: "layout",
    description: "Wrapping horizontal cluster.",
    ruleIds: ["rule.foundations.semantic-tokens"],
    states: ["idle"],
    importName: "Cluster",
    example: `<Cluster>…</Cluster>`,
  },
  {
    slug: "grid",
    name: "Grid",
    family: "layout",
    description: "Responsive auto-fit grid.",
    ruleIds: ["rule.foundations.semantic-tokens"],
    states: ["idle"],
    importName: "Grid",
    example: `<Grid>…</Grid>`,
  },
  {
    slug: "container",
    name: "Container",
    family: "layout",
    description: "Centered max-width content shell.",
    ruleIds: ["rule.foundations.semantic-tokens"],
    states: ["idle"],
    importName: "Container",
    example: `<Container>…</Container>`,
  },
  {
    slug: "visually-hidden",
    name: "VisuallyHidden",
    family: "layout",
    description: "Screen-reader-only text.",
    ruleIds: ["rule.a11y.wcag-aa"],
    states: ["idle"],
    importName: "VisuallyHidden",
    example: `<VisuallyHidden>Extra context</VisuallyHidden>`,
  },
];

export function getComponent(slug: string) {
  return componentCatalog.find((c) => c.slug === slug);
}
