import type { Locale } from "./i18n";

const content = {
  en: {
    hero: {
      registration: "AWESOMEDS · v2026.07 · CANON → BUILD → VERIFY",
      eyebrow: "The evidence-first design instrument",
      titleLead: "Taste you can",
      titleWord: "PROVE",
      titleTrail: ".",
      description:
        "A living Canon, semantic tokens, accessible React components, and motion contracts — every one traceable to a first-party source. Built for people who ship, and the AI agents shipping beside them.",
      primaryAction: "Start with the Canon",
      primaryHref: "/canon",
      secondaryAction: "See how it works",
      secondaryHref: "#how-it-works",
      trustLabel: "Live repository truth",
      graphHealthy: "Evidence graph healthy",
      graphNeedsReview: "Evidence graph needs review",
      rulesLabel: "canonical rules",
      sourcesLabel: "structured sources",
      componentsLabel: "live components",
      freshnessLabel: "references in cadence",
    },
    calibrator: {
      eyebrow: "Live proof instrument",
      title: "Calibrate any decision.",
      hint: "Pick an intent. Watch it resolve — source, rule, artifact, verdict.",
      selectLabel: "Design intent",
      intents: [
        "Trace a doctrine claim to maintained evidence",
        "Scale UI through semantic tokens",
        "Ship every interactive component state",
        "Bound a generative agent to approved contracts",
      ],
      calibrating: "Calibrating…",
      calibrated: "Calibrated",
      stageSource: "Source",
      stageRule: "Rule",
      stageArtifact: "Artifact",
      stageVerdict: "Verdict",
      verified: "Traceable",
      needsReview: "Needs review",
      openLabel: "Open",
    },
    how: {
      eyebrow: "How it works",
      title: "Read. Build. Prove.",
      description:
        "One production loop, three moves — Start, Build, Verify. Explore (the Atlas, AI guidance, and brand) is the reference layer you can open at any step. Agents get finite, safe choices; people keep judgment and the final call.",
      steps: [
        {
          key: "01",
          tag: "START",
          title: "Read the Canon to decide",
          body: "Begin from principles and rule IDs, not screenshots or taste claims.",
          meta: "canon · principles",
          action: "Enter the Canon",
          href: "/canon",
        },
        {
          key: "02",
          tag: "BUILD",
          title: "Compose live contracts",
          body: "Assemble semantic tokens, complete component states, and purpose-led motion.",
          meta: "foundations · components · motion",
          action: "Open components",
          href: "/components",
        },
        {
          key: "03",
          tag: "VERIFY",
          title: "Prove every choice",
          body: "Check each outcome against its sources, artifacts, and tests, then read the live system status.",
          meta: "review · status · playground",
          action: "Open system status",
          href: "/status",
        },
      ],
    },
    scale: {
      eyebrow: "Aesthetics with receipts",
      lead: "Not opinions.",
      leadEmphasis: "Readings.",
      description:
        "Design references sell taste. AwesomeDS ships taste with a paper trail you can validate — locally, in CI, or from an agent.",
      metrics: [
        { label: "canonical rules", sub: "each linked to evidence" },
        { label: "structured sources", sub: "freshness-tracked" },
        { label: "live components", sub: "full state contracts" },
        { label: "coverage", sub: "rules with implementation", suffix: "%" },
      ],
    },
    build: {
      eyebrow: "Live components",
      title: "The documentation is executable.",
      description:
        "These are the real @awesome-ds/react primitives — labels, focus behavior, status feedback, and state contracts, not a static mockup.",
      actionCard: "Action contract",
      primary: "Generate brief",
      secondary: "Review evidence",
      loading: "Checking sources",
      fieldLabel: "Design intent",
      fieldHint: "Specific intent gives agents a safer decision boundary.",
      fieldPlaceholder: "A calm approval flow for mobile reviewers",
      statusTitle: "Evidence connected",
      statusBody: "This pattern cites canonical rules and first-party sources.",
      progress: "Canon implementation coverage",
      browse: "Browse all components",
    },
    canon: {
      eyebrow: "The Canon",
      title: "Rules designed to become action.",
      description:
        "Each rule carries guidance, do and don’t examples, supporting references, implementation links, and a verification contract.",
      browse: "View all rules",
      guidance: "Guidance",
      evidence: "Evidence",
      implementation: "Implementation",
      verification: "Verification",
    },
    foundations: {
      eyebrow: "Foundations",
      title: "A visual language built for judgment.",
      description:
        "Semantic color, deliberate typography, 4/8-point rhythm — one stable contract across light, dark, high-contrast, English, and Japanese.",
      colorTitle: "Color is a role",
      colorBody: "One ember signal for interaction. Status colors carry only status. Surfaces build depth with tone and hairlines.",
      typeTitle: "Type carries the voice",
      typeBody: "Editorial display meets a precise UI sans. Japanese keeps its own rhythm, spacing, and line-breaking.",
      typeSample: "Precision with room to breathe.",
      typeSampleJa: "精度と余白を、ひとつの体系に。",
      tokenLabels: ["Canvas", "Surface", "Ink", "Signal", "Success"],
      openFoundations: "Open foundations",
    },
    motion: {
      eyebrow: "Motion contracts",
      title: "Quiet movement with a job to do.",
      description:
        "Replay real intent-based recipes. Each declares where it belongs, where it does not, and what replaces it under reduced motion.",
      replay: "Replay motion",
      replayed: "Motion replayed",
      browse: "Inspect all motion recipes",
      demos: [
        { intent: "enter", label: "Enter", description: "Introduce new content without layout shift." },
        { intent: "feedback", label: "Feedback", description: "Acknowledge an explicit user action." },
        { intent: "reveal", label: "Reveal", description: "Guide attention once, then become still." },
      ],
    },
    atlas: {
      eyebrow: "Reference Atlas",
      title: "Trust signals belong beside the claim.",
      description:
        "Sources show ownership, evidence class, last verification, drift risk, freshness, and the rules they support. A logo wall is not provenance.",
      verified: "Verified",
      freshness: "Freshness",
      linkedRules: "Linked rules",
      browse: "Explore every source",
    },
    brand: {
      eyebrow: "The AwesomeDS brand",
      title: "One personality. Every medium.",
      description:
        "AwesomeDS has its own brand system — proven by the same rules it hands you. Study it as a worked example, then generate your own with /MakeAwesomeDS.",
      grammar: [
        { mark: "proof", term: "The proof mark", body: "An ember registration glyph: taste that points back at its evidence." },
        { mark: "signal", term: "One ember signal", body: "One authored interaction color. It may recur as a coherent registration system, but never a second competing accent." },
        { mark: "grid", term: "The blueprint plane", body: "A faint measuring field behind content. The white reading surface stays." },
        { mark: "label", term: "Registration labels", body: "Monospace coordinates over adjectives. The instrument reports; it doesn’t sell." },
      ],
      action: "Read the brand bible",
      href: "/brand",
    },
    agents: {
      eyebrow: "Adopt in four moves",
      title: "Bound the agent. Keep the human in charge.",
      description:
        "AwesomeDS hands coding agents a compact operating contract while preserving evidence, approval boundaries, fallbacks, and recovery.",
      steps: [
        { title: "Load the contract", body: "Read DESIGN.md and the relevant Canon modules." },
        { title: "Name the rules", body: "Select rule IDs and declare the user need and risk." },
        { title: "Compose approved UI", body: "Use semantic tokens and catalog components only." },
        { title: "Verify and report", body: "Test states, accessibility, provenance, and freshness." },
      ],
      codeLabel: "Agent instruction",
      code: "Read DESIGN.md → cite rule.* IDs → compose @awesome-ds/react → verify states + a11y + evidence",
      open: "Open AI design guidance",
    },
    closing: {
      eyebrow: "Four ways in",
      title: "Design knowledge should stay inspectable.",
      quad: [
        { tag: "START", title: "Read the Canon", href: "/canon" },
        { tag: "EXPLORE", title: "Trace the Atlas", href: "/references" },
        { tag: "BUILD", title: "Compose components", href: "/components" },
        { tag: "VERIFY", title: "Check system status", href: "/status" },
      ],
    },
  },
  ja: {
    hero: {
      registration: "AWESOMEDS · v2026.07 · 体系 → 実装 → 検証",
      eyebrow: "根拠を起点にするデザインの計器",
      titleLead: "証明できる、",
      titleWord: "PROVE",
      titleTrail: "",
      description:
        "進化し続ける体系、セマンティックトークン、アクセシブルなReactコンポーネント、モーション契約。そのすべてを一次情報まで辿れます。作る人と、隣で作るAIエージェントのために。",
      primaryAction: "体系から始める",
      primaryHref: "/canon",
      secondaryAction: "仕組みを見る",
      secondaryHref: "#how-it-works",
      trustLabel: "リポジトリの現在値",
      graphHealthy: "根拠グラフは正常",
      graphNeedsReview: "根拠グラフを要確認",
      rulesLabel: "件の標準ルール",
      sourcesLabel: "件の構造化情報源",
      componentsLabel: "個のライブコンポーネント",
      freshnessLabel: "件が確認周期内",
    },
    calibrator: {
      eyebrow: "ライブ根拠インストルメント",
      title: "あらゆる判断を較正する。",
      hint: "意図を選ぶと、情報源・ルール・成果物・判定へ解決されます。",
      selectLabel: "デザインの意図",
      intents: [
        "標準ルールを保守された根拠へ結びつける",
        "セマンティックトークンでUIを拡張する",
        "インタラクティブ部品の全状態を実装する",
        "生成AIを承認済みの契約内に制約する",
      ],
      calibrating: "較正中…",
      calibrated: "較正完了",
      stageSource: "情報源",
      stageRule: "ルール",
      stageArtifact: "成果物",
      stageVerdict: "判定",
      verified: "追跡可能",
      needsReview: "要確認",
      openLabel: "開く",
    },
    how: {
      eyebrow: "仕組み",
      title: "読む。作る。証明する。",
      description:
        "ひとつの制作ループに、3つの動き ― はじめる・つくる・確かめる。見つける（アトラス・AI指針・ブランド）は、どの段階でも開ける参照レイヤーです。AIには有限で安全な選択肢を、人には判断と最終決定を残します。",
      steps: [
        {
          key: "01",
          tag: "START",
          title: "体系を読んで判断する",
          body: "スクリーンショットや感覚ではなく、原則とルールIDから始めます。",
          meta: "体系 · 原則",
          action: "体系を開く",
          href: "/canon",
        },
        {
          key: "02",
          tag: "BUILD",
          title: "実行可能な契約で作る",
          body: "セマンティックトークン、全状態を備えた部品、目的起点の動きを組みます。",
          meta: "基礎 · コンポーネント · モーション",
          action: "コンポーネントを開く",
          href: "/components",
        },
        {
          key: "03",
          tag: "VERIFY",
          title: "すべての選択を証明する",
          body: "各結果を情報源・成果物・テストと照らし合わせ、稼働中のシステム状態を確認します。",
          meta: "レビュー · ステータス · プレイグラウンド",
          action: "システム状態を開く",
          href: "/status",
        },
      ],
    },
    scale: {
      eyebrow: "根拠を伴う美意識",
      lead: "意見ではなく、",
      leadEmphasis: "計測値を。",
      description:
        "多くのデザイン集は美意識を売ります。AwesomeDSは、ローカルでもCIでもAIからでも検証できる証跡とともに美意識を届けます。",
      metrics: [
        { label: "件の標準ルール", sub: "すべて根拠に接続" },
        { label: "件の構造化情報源", sub: "鮮度を追跡" },
        { label: "個のライブ部品", sub: "全状態を契約化" },
        { label: "実装率", sub: "実装済みの標準ルール", suffix: "%" },
      ],
    },
    build: {
      eyebrow: "ライブコンポーネント",
      title: "ドキュメントそのものが動く。",
      description:
        "静止画ではなく、実際の @awesome-ds/react プリミティブです。ラベル、フォーカス、状態フィードバック、操作契約をその場で確認できます。",
      actionCard: "操作契約",
      primary: "ブリーフを生成",
      secondary: "根拠を確認",
      loading: "情報源を確認中",
      fieldLabel: "デザインの意図",
      fieldHint: "意図を具体化すると、AIの安全な判断範囲を定められます。",
      fieldPlaceholder: "モバイル審査者向けの落ち着いた承認フロー",
      statusTitle: "根拠に接続済み",
      statusBody: "このパターンは標準ルールと一次情報を参照しています。",
      progress: "標準ルールの実装率",
      browse: "すべてのコンポーネントを見る",
    },
    canon: {
      eyebrow: "標準体系",
      title: "実践へ変換できるルール。",
      description: "各ルールには、ガイダンス、推奨・非推奨、根拠リファレンス、実装リンク、検証契約があります。",
      browse: "すべてのルールを見る",
      guidance: "ガイダンス",
      evidence: "根拠",
      implementation: "実装",
      verification: "検証",
    },
    foundations: {
      eyebrow: "基礎",
      title: "判断を支える視覚言語。",
      description: "セマンティックカラー、意図ある文字組み、4/8ポイントのリズム。ライト、ダーク、ハイコントラスト、日本語、英語を通して安定した契約です。",
      colorTitle: "色には役割がある",
      colorBody: "操作色はエンバー一色。状態色は状態だけを伝え、面と細い境界線で奥行きを作ります。",
      typeTitle: "文字が声をつくる",
      typeBody: "編集的な見出しと精密なUI書体を組み合わせ、日本語には固有の行間、字間、改行規則を適用します。",
      typeSample: "Precision with room to breathe.",
      typeSampleJa: "精度と余白を、ひとつの体系に。",
      tokenLabels: ["背景", "サーフェス", "文字", "シグナル", "成功"],
      openFoundations: "基礎を見る",
    },
    motion: {
      eyebrow: "モーション契約",
      title: "役割を終えたら、静かになる動き。",
      description: "目的別の実レシピを再生できます。すべてのレシピが、使う場面、使わない場面、動きを減らす設定での代替を明示します。",
      replay: "動きを再生",
      replayed: "動きを再生しました",
      browse: "すべてのモーションを見る",
      demos: [
        { intent: "enter", label: "表示", description: "レイアウトをずらさず、新しい内容を示します。" },
        { intent: "feedback", label: "フィードバック", description: "明示的な操作に、短く応答します。" },
        { intent: "reveal", label: "段階表示", description: "一度だけ視線を導き、その後は静止します。" },
      ],
    },
    atlas: {
      eyebrow: "リファレンス・アトラス",
      title: "信頼の手がかりを、主張のそばに。",
      description: "提供元、証拠区分、最終確認日、変化リスク、鮮度、関連ルールを表示します。ロゴの一覧だけでは根拠になりません。",
      verified: "最終確認",
      freshness: "鮮度",
      linkedRules: "関連ルール",
      browse: "すべての情報源を見る",
    },
    brand: {
      eyebrow: "AwesomeDSのブランド",
      title: "ひとつの人格を、すべての媒体へ。",
      description:
        "AwesomeDS自身にもブランドDSがあります。あなたに渡すのと同じルールで証明済みです。実例として学び、/MakeAwesomeDS で独自のブランドを生成できます。",
      grammar: [
        { mark: "proof", term: "プルーフマーク", body: "エンバーの登録記号。根拠を指し示す美意識。" },
        { mark: "signal", term: "単一のエンバー", body: "操作色はひとつ。ひとつの登録システムとして繰り返すことはあっても、二つ目の対抗色にはしません。" },
        { mark: "grid", term: "設計図の面", body: "内容の背後の淡い計測面。白い読み面は保たれます。" },
        { mark: "label", term: "登録ラベル", body: "形容詞より座標を。計器は報告し、売り込みません。" },
      ],
      action: "ブランド・バイブルを読む",
      href: "/brand",
    },
    agents: {
      eyebrow: "4つの動きで導入",
      title: "AIの範囲を定め、人が主導する。",
      description: "AwesomeDSは、根拠、承認境界、代替手段、復旧経路を保ちながら、コーディングエージェントへ短く実行可能な契約を渡します。",
      steps: [
        { title: "契約を読む", body: "DESIGN.mdと関連する標準モジュールを読みます。" },
        { title: "ルールを名指す", body: "ルールID、利用者の目的、リスクを宣言します。" },
        { title: "承認済みUIを組む", body: "セマンティックトークンと登録済み部品だけを使います。" },
        { title: "検証して報告する", body: "状態、アクセシビリティ、根拠、鮮度を確認します。" },
      ],
      codeLabel: "エージェントへの指示",
      code: "DESIGN.mdを読む → rule.* IDを引用 → @awesome-ds/reactで構成 → 状態・a11y・根拠を検証",
      open: "AIデザイン指針を開く",
    },
    closing: {
      eyebrow: "4つの入口",
      title: "デザイン知識は、検証できる状態に。",
      quad: [
        { tag: "START", title: "体系を読む", href: "/canon" },
        { tag: "EXPLORE", title: "アトラスを辿る", href: "/references" },
        { tag: "BUILD", title: "部品を組む", href: "/components" },
        { tag: "VERIFY", title: "システム状態を見る", href: "/status" },
      ],
    },
  },
} as const;

export function getHomeContent(locale: Locale) {
  return content[locale];
}
