import type { Locale } from "./i18n";

const content = {
  en: {
    hero: {
      eyebrow: "AI Design Intelligence · Evidence first",
      title: "The design bible that agents can actually use.",
      description:
        "AwesomeDS turns first-party evidence into a living Canon, semantic tokens, accessible React components, motion contracts, and verification-ready instructions.",
      primaryAction: "Read the Canon",
      secondaryAction: "Open the Reference Atlas",
      trustLabel: "Live repository truth",
      graphHealthy: "Evidence graph healthy",
      graphNeedsReview: "Evidence graph needs review",
      freshnessLabel: "references in cadence",
      rulesLabel: "canonical rules",
      sourcesLabel: "structured sources",
      componentsLabel: "live components",
    },
    proof: {
      eyebrow: "From question to verified interface",
      title: "One evidence chain. No invented design truth.",
      description:
        "Every recommendation can be traced through a source, a rule, an implementation artifact, and a test. Agents get finite choices; people keep judgment and control.",
      input: "Product intent",
      inputValue: "Design a trustworthy approval flow",
      source: "Primary evidence",
      rule: "Canonical contract",
      output: "Approved UI",
      verify: "Verification",
      verified: "Traceable",
    },
    paths: {
      eyebrow: "What AwesomeDS enables",
      title: "Read it like a publication. Use it like infrastructure.",
      items: [
        {
          index: "01",
          title: "Decide with the Canon",
          body: "Start from principles and rule IDs, not screenshots or taste claims.",
          meta: "Principles · foundations · interaction",
          href: "/canon",
          action: "Browse the Canon",
        },
        {
          index: "02",
          title: "Build with live contracts",
          body: "Compose semantic tokens, complete component states, and purpose-led motion.",
          meta: "Components · motion · playground",
          href: "/components",
          action: "Inspect components",
        },
        {
          index: "03",
          title: "Prove with evidence",
          body: "Follow every conclusion back to first-party sources, dates, caveats, and artifacts.",
          meta: "Atlas · freshness · system status",
          href: "/references",
          action: "Trace the evidence",
        },
      ],
    },
    canon: {
      eyebrow: "The Canon",
      title: "Rules designed to become action.",
      description:
        "Each rule carries guidance, do and don’t examples, supporting references, implementation links, and a verification contract.",
      browse: "View all rules",
      guidance: "Guidance",
      evidence: "Evidence",
      implementation: "Implementation",
      verification: "Verification",
    },
    foundations: {
      eyebrow: "Current foundations",
      title: "A visual language built for judgment, not decoration.",
      description:
        "Semantic color, deliberate typography, 4/8-point rhythm, and state-aware motion form one stable contract across light, dark, high-contrast, English, and Japanese.",
      colorTitle: "Color is a role",
      colorBody: "One interaction accent. Status colors only carry status. Surfaces create depth with tone and hairlines.",
      typeTitle: "Type carries the voice",
      typeBody: "Editorial display type meets a precise UI sans. Japanese keeps its own rhythm, spacing, and line-breaking rules.",
      typeSample: "Precision with room to breathe.",
      typeSampleJa: "精度と余白を、ひとつの体系に。",
      tokenLabels: ["Canvas", "Surface", "Ink", "Accent", "Success"],
      openFoundations: "Open foundations",
    },
    components: {
      eyebrow: "Live components",
      title: "The documentation is executable.",
      description:
        "These are the real AwesomeDS React primitives, shown with labels, focus behavior, status feedback, and state contracts—not a static mockup.",
      actionCard: "Action contract",
      primary: "Generate brief",
      secondary: "Review evidence",
      loading: "Checking sources",
      fieldLabel: "Design intent",
      fieldHint: "Specific intent gives agents a safer decision boundary.",
      fieldPlaceholder: "A calm approval flow for mobile reviewers",
      statusTitle: "Evidence connected",
      statusBody: "This pattern cites canonical rules and first-party sources.",
      progress: "Canon implementation coverage",
      browse: "Browse all components",
    },
    motion: {
      eyebrow: "Motion contracts",
      title: "Quiet movement with a job to do.",
      description:
        "Replay real intent-based recipes. Every recipe declares where it belongs, where it does not, and what replaces it when reduced motion is enabled.",
      replay: "Replay motion",
      replayed: "Motion replayed",
      browse: "Inspect all motion recipes",
      demos: [
        { intent: "enter", label: "Enter", description: "Introduce new content without layout shift." },
        { intent: "feedback", label: "Feedback", description: "Acknowledge an explicit user action." },
        { intent: "reveal", label: "Reveal", description: "Guide attention once, then become still." },
      ],
    },
    atlas: {
      eyebrow: "Reference Atlas",
      title: "Trust signals belong beside the claim.",
      description:
        "Sources show ownership, evidence class, last verification, drift risk, freshness, and the rules they support. A logo wall is not provenance.",
      source: "Source",
      verified: "Verified",
      freshness: "Freshness",
      linkedRules: "Linked rules",
      browse: "Explore every source",
    },
    agents: {
      eyebrow: "Practical agent workflow",
      title: "Bound the agent. Keep the human in charge.",
      description:
        "AwesomeDS gives coding agents a compact operating contract while preserving evidence, approval boundaries, fallbacks, and recovery.",
      steps: [
        { title: "Load the contract", body: "Read DESIGN.md and the relevant Canon modules." },
        { title: "Name the rules", body: "Select rule IDs and declare the user need and risk." },
        { title: "Compose approved UI", body: "Use semantic tokens and catalog components only." },
        { title: "Verify and report", body: "Test states, accessibility, provenance, and freshness." },
      ],
      codeLabel: "Agent instruction",
      code: "Read DESIGN.md → cite rule.* IDs → compose @awesome-ds/react → verify states + a11y + evidence",
      open: "Open AI design guidance",
    },
    closing: {
      eyebrow: "Design knowledge should stay inspectable",
      title: "Build with taste. Leave an evidence trail.",
      primary: "Start with the Canon",
      secondary: "Check system status",
    },
  },
  ja: {
    hero: {
      eyebrow: "AIデザイン・インテリジェンス · 根拠を起点に",
      title: "人が読めて、AIが実践できるデザインのバイブル",
      description:
        "AwesomeDSは、一次情報を、進化し続ける体系、セマンティックトークン、アクセシブルなReactコンポーネント、モーション契約、検証可能な指示へ変換します。",
      primaryAction: "体系を読む",
      secondaryAction: "リファレンス・アトラスを開く",
      trustLabel: "リポジトリの現在値",
      graphHealthy: "根拠グラフは正常",
      graphNeedsReview: "根拠グラフを要確認",
      freshnessLabel: "件が確認周期内",
      rulesLabel: "件の標準ルール",
      sourcesLabel: "件の構造化情報源",
      componentsLabel: "個のライブコンポーネント",
    },
    proof: {
      eyebrow: "問いから、検証済みUIまで",
      title: "ひとつながりの根拠。推測で作らない。",
      description:
        "すべての提案を、情報源、ルール、実装成果物、テストまで遡れます。AIには有限の選択肢を、人には判断と主導権を残します。",
      input: "プロダクトの意図",
      inputValue: "信頼できる承認フローを設計する",
      source: "一次情報",
      rule: "標準契約",
      output: "承認済みUI",
      verify: "検証",
      verified: "追跡可能",
    },
    paths: {
      eyebrow: "AwesomeDSでできること",
      title: "刊行物のように読み、基盤のように使う。",
      items: [
        { index: "01", title: "体系から判断する", body: "スクリーンショットや感覚ではなく、原則とルールIDから始めます。", meta: "原則 · 基礎 · インタラクション", href: "/canon", action: "体系を見る" },
        { index: "02", title: "実行可能な契約で作る", body: "セマンティックトークン、全状態を備えた部品、目的起点の動きを組み合わせます。", meta: "コンポーネント · モーション · プレイグラウンド", href: "/components", action: "部品を見る" },
        { index: "03", title: "根拠で証明する", body: "すべての結論を、一次情報、確認日、注意点、成果物まで遡れます。", meta: "アトラス · 鮮度 · システム状態", href: "/references", action: "根拠を辿る" },
      ],
    },
    canon: {
      eyebrow: "標準体系",
      title: "実践へ変換できるルール。",
      description: "各ルールには、ガイダンス、推奨・非推奨、根拠リファレンス、実装リンク、検証契約があります。",
      browse: "すべてのルールを見る",
      guidance: "ガイダンス",
      evidence: "根拠",
      implementation: "実装",
      verification: "検証",
    },
    foundations: {
      eyebrow: "現在の基礎",
      title: "装飾ではなく、判断を支える視覚言語。",
      description: "セマンティックカラー、意図ある文字組み、4/8ポイントのリズム、状態を伝える動きが、ライト、ダーク、ハイコントラスト、日本語、英語を通して安定した契約を作ります。",
      colorTitle: "色には役割がある",
      colorBody: "操作色はひとつ。状態色は状態だけを伝え、面と細い境界線で奥行きを作ります。",
      typeTitle: "文字が声をつくる",
      typeBody: "編集的な見出しと精密なUI書体を組み合わせ、日本語には固有の行間、字間、改行規則を適用します。",
      typeSample: "Precision with room to breathe.",
      typeSampleJa: "精度と余白を、ひとつの体系に。",
      tokenLabels: ["背景", "サーフェス", "文字", "操作", "成功"],
      openFoundations: "基礎を見る",
    },
    components: {
      eyebrow: "ライブコンポーネント",
      title: "ドキュメントそのものが動く。",
      description: "静止画ではなく、実際のAwesomeDS Reactプリミティブです。ラベル、フォーカス、状態フィードバック、操作契約をその場で確認できます。",
      actionCard: "操作契約",
      primary: "ブリーフを生成",
      secondary: "根拠を確認",
      loading: "情報源を確認中",
      fieldLabel: "デザインの意図",
      fieldHint: "意図を具体化すると、AIの安全な判断範囲を定められます。",
      fieldPlaceholder: "モバイル審査者向けの落ち着いた承認フロー",
      statusTitle: "根拠に接続済み",
      statusBody: "このパターンは標準ルールと一次情報を参照しています。",
      progress: "標準ルールの実装率",
      browse: "すべてのコンポーネントを見る",
    },
    motion: {
      eyebrow: "モーション契約",
      title: "役割を終えたら、静かになる動き。",
      description: "目的別の実レシピを再生できます。すべてのレシピが、使う場面、使わない場面、動きを減らす設定での代替を明示します。",
      replay: "動きを再生",
      replayed: "動きを再生しました",
      browse: "すべてのモーションを見る",
      demos: [
        { intent: "enter", label: "表示", description: "レイアウトをずらさず、新しい内容を示します。" },
        { intent: "feedback", label: "フィードバック", description: "明示的な操作に、短く応答します。" },
        { intent: "reveal", label: "段階表示", description: "一度だけ視線を導き、その後は静止します。" },
      ],
    },
    atlas: {
      eyebrow: "リファレンス・アトラス",
      title: "信頼の手がかりを、主張のそばに。",
      description: "提供元、証拠区分、最終確認日、変化リスク、鮮度、関連ルールを表示します。ロゴの一覧だけでは根拠になりません。",
      source: "情報源",
      verified: "最終確認",
      freshness: "鮮度",
      linkedRules: "関連ルール",
      browse: "すべての情報源を見る",
    },
    agents: {
      eyebrow: "AIエージェントの実践フロー",
      title: "AIの範囲を定め、人が主導する。",
      description: "AwesomeDSは、根拠、承認境界、代替手段、復旧経路を保ちながら、コーディングエージェントへ短く実行可能な契約を渡します。",
      steps: [
        { title: "契約を読む", body: "DESIGN.mdと関連する標準モジュールを読みます。" },
        { title: "ルールを名指す", body: "ルールID、利用者の目的、リスクを宣言します。" },
        { title: "承認済みUIを組む", body: "セマンティックトークンと登録済み部品だけを使います。" },
        { title: "検証して報告する", body: "状態、アクセシビリティ、根拠、鮮度を確認します。" },
      ],
      codeLabel: "エージェントへの指示",
      code: "DESIGN.mdを読む → rule.* IDを引用 → @awesome-ds/reactで構成 → 状態・a11y・根拠を検証",
      open: "AIデザイン指針を開く",
    },
    closing: {
      eyebrow: "デザイン知識は、検証できる状態に",
      title: "美意識をもって作り、根拠を残す。",
      primary: "体系から始める",
      secondary: "システム状態を見る",
    },
  },
} as const;

export function getHomeContent(locale: Locale) {
  return content[locale];
}
