import type { Locale } from "./i18n";

const content = {
  en: {
    hero: {
      kicker: "Design bible · 2026",
      title: "Stop shipping",
      titleAccent: "AI slop.",
      titleTrail: "Ship taste.",
      description:
        "AwesomeDS is the taste layer for people and AI agents — a living Canon, semantic tokens, accessible React, and motion with a job. Built so the next UI you generate feels human, not average.",
      primaryAction: "Explore the system",
      primaryHref: "/canon",
      secondaryAction: "Install the skills",
      secondaryHref: "#install",
      liveLabel: "Live repository truth",
      graphHealthy: "Evidence graph healthy",
      graphNeedsReview: "Evidence graph needs review",
      rulesLabel: "canon rules",
      sourcesLabel: "cited sources",
      componentsLabel: "live components",
      skillsLabel: "agent skills",
    },
    promise: {
      eyebrow: "Why it exists",
      title: "Models default to the median. You need a point of view.",
      body: "Ask an LLM for a landing page and you get Inter, a purple gradient, three emoji cards. AwesomeDS steers off the center — with doctrine you can open, contracts you can run, and evidence you can verify.",
      cards: [
        {
          tag: "DOCTRINE",
          title: "Opinionated knowledge",
          body: "Philosophy, foundations, brand, motion, a11y — code-embedded, source-cited.",
          href: "/canon",
          action: "Open Canon",
        },
        {
          tag: "EXECUTABLE",
          title: "Tokens + React + motion",
          body: "Semantic OKLCH tokens, full-state components, purpose-led motion recipes.",
          href: "/components",
          action: "Browse components",
        },
        {
          tag: "VERBS",
          title: "Five agent skills",
          body: "AwesomeDS · MakeAwesomeDS · AwesomeHTML · AwesomeReview · AwesomeMotion.",
          href: "/ai-design",
          action: "Agent guidance",
        },
      ],
    },
    character: {
      eyebrow: "Meet Dotto",
      title: "A little joy in the system.",
      body: "Serious systems don’t have to feel sterile. Dotto is the mascot of the CMY mark — playful motion that still respects reduced-motion preferences.",
      moods: [
        { mood: "wave" as const, label: "Waves hello" },
        { mood: "think" as const, label: "Thinks carefully" },
        { mood: "cheer" as const, label: "Cheers a ship" },
      ],
    },
    how: {
      eyebrow: "How it works",
      title: "Read. Build. Prove.",
      description:
        "One production loop. Agents get finite, safe choices. People keep judgment and the final call.",
      steps: [
        {
          key: "01",
          tag: "START",
          title: "Read the Canon",
          body: "Begin from principles and rule IDs — not screenshots or vibes.",
          meta: "canon · principles",
          action: "Enter the Canon",
          href: "/canon",
        },
        {
          key: "02",
          tag: "BUILD",
          title: "Compose live contracts",
          body: "Semantic tokens, complete component states, purpose-led motion.",
          meta: "foundations · components · motion",
          action: "Open components",
          href: "/components",
        },
        {
          key: "03",
          tag: "VERIFY",
          title: "Prove every choice",
          body: "Trace claims to sources. Run gates. Check system status.",
          meta: "review · reports · status",
          action: "Open status",
          href: "/status",
        },
      ],
    },
    scale: {
      eyebrow: "Aesthetics with receipts",
      lead: "Not opinions.",
      leadEmphasis: "Readings.",
      description:
        "Design references sell taste. AwesomeDS ships taste with a paper trail you can validate — locally, in CI, or from an agent.",
      metrics: [
        { label: "canonical rules", sub: "each linked to evidence" },
        { label: "structured sources", sub: "freshness-tracked" },
        { label: "live components", sub: "full state contracts" },
        { label: "coverage", sub: "rules with implementation", suffix: "%" },
      ],
    },
    spectrum: {
      eyebrow: "The CMY identity",
      title: "Three primaries. One designed spectrum.",
      body: "Cyan · magenta · yellow — subtractive mixing as the logomark. An OKLCH spectrum as the signature stripe. White paper, dark ink. Never a dark hero.",
      openBrand: "Read the brand bible",
    },
    build: {
      eyebrow: "Live components",
      title: "The documentation is executable.",
      description:
        "Real @awesome-ds/react primitives — labels, focus, status, and state contracts. Not a static mockup.",
      actionCard: "Action contract",
      primary: "Generate brief",
      secondary: "Review evidence",
      loading: "Checking sources",
      fieldLabel: "Design intent",
      fieldHint: "Specific intent gives agents a safer decision boundary.",
      fieldPlaceholder: "A calm approval flow for mobile reviewers",
      statusTitle: "Evidence connected",
      statusBody: "This pattern cites canonical rules and first-party sources.",
      progress: "Canon implementation coverage",
      browse: "Browse all components",
    },
    motion: {
      eyebrow: "Motion library",
      title: "Movement with a job to do.",
      description:
        "Replay intent-based recipes. Each declares where it belongs, where it does not, and what replaces it under reduced motion.",
      replay: "Replay motion",
      replayed: "Motion replayed",
      browse: "Inspect all motion recipes",
      demos: [
        {
          intent: "enter",
          label: "Enter",
          description: "Introduce new content without layout shift.",
        },
        {
          intent: "feedback",
          label: "Feedback",
          description: "Acknowledge an explicit user action.",
        },
        {
          intent: "reveal",
          label: "Reveal",
          description: "Guide attention once, then become still.",
        },
      ],
    },
    install: {
      eyebrow: "Quick start",
      title: "Point an agent here. Or install the skills.",
      tip: "Tell the agent to read design-system/INDEX.md first, then open only the modules it needs.",
      code: "git clone https://github.com/Yu-aimaker/AwesomeDesignSystem.git\ncd AwesomeDesignSystem\n./install.sh",
      note: "Symlinks the five skills into ~/.claude/skills. Keep the repo in place so pulls update skills.",
      skills: [
        { name: "/AwesomeDS", use: "Build or refine any UI with taste" },
        { name: "/MakeAwesomeDS", use: "Generate a brand’s own design system" },
        { name: "/AwesomeHTML", use: "Polish notes into a single-file HTML doc" },
        { name: "/AwesomeReview", use: "Audit UI for slop and a11y failures" },
        { name: "/AwesomeMotion", use: "Design purpose-driven motion" },
      ],
    },
    atlas: {
      eyebrow: "Reference Atlas",
      title: "Trust signals belong beside the claim.",
      description:
        "Ownership, evidence class, last verification, drift risk, freshness, and linked rules. A logo wall is not provenance.",
      verified: "Verified",
      freshness: "Freshness",
      linkedRules: "Linked rules",
      browse: "Explore every source",
    },
    closing: {
      eyebrow: "Four ways in",
      title: "Pick a door. Leave with a system.",
      quad: [
        { tag: "START", title: "Read the Canon", href: "/canon" },
        { tag: "EXPLORE", title: "Trace the Atlas", href: "/references" },
        { tag: "BUILD", title: "Compose components", href: "/components" },
        { tag: "VERIFY", title: "Check system status", href: "/status" },
      ],
    },
  },
  ja: {
    hero: {
      kicker: "デザインのバイブル · 2026",
      title: "AIスロップを",
      titleAccent: "やめよう。",
      titleTrail: "美意識を出荷しよう。",
      description:
        "AwesomeDSは、人とAIエージェントのためのテイスト層です。生きた体系、セマンティックトークン、アクセシブルなReact、役割のあるモーション。次に生成するUIが、平均ではなく人間味を持つように。",
      primaryAction: "システムを見る",
      primaryHref: "/canon",
      secondaryAction: "スキルを入れる",
      secondaryHref: "#install",
      liveLabel: "リポジトリの現在値",
      graphHealthy: "根拠グラフは正常",
      graphNeedsReview: "根拠グラフを要確認",
      rulesLabel: "件の標準ルール",
      sourcesLabel: "件の情報源",
      componentsLabel: "個のライブ部品",
      skillsLabel: "個のエージェントスキル",
    },
    promise: {
      eyebrow: "なぜ存在するか",
      title: "モデルは中央値に寄る。視点が必要だ。",
      body: "LLMにLPを頼むと、Inter・紫グラデ・絵文字カード3枚が返る。AwesomeDSは中央からずらす舵取り——開ける教義、実行できる契約、検証できる根拠。",
      cards: [
        {
          tag: "DOCTRINE",
          title: "意見のある知識",
          body: "哲学・基礎・ブランド・モーション・a11y。コード埋め込み、出典付き。",
          href: "/canon",
          action: "体系を開く",
        },
        {
          tag: "EXECUTABLE",
          title: "トークン + React + 動き",
          body: "セマンティックOKLCH、全状態コンポーネント、目的起点のモーション。",
          href: "/components",
          action: "部品を見る",
        },
        {
          tag: "VERBS",
          title: "5つのエージェントスキル",
          body: "AwesomeDS · MakeAwesomeDS · AwesomeHTML · AwesomeReview · AwesomeMotion。",
          href: "/ai-design",
          action: "AI指針へ",
        },
      ],
    },
    character: {
      eyebrow: "Dottoに会う",
      title: "体系に、少しの遊び心を。",
      body: "真剣なシステムは無味である必要はない。DottoはCMYマークのマスコット。遊びのある動きでも、動きを減らす設定を尊重します。",
      moods: [
        { mood: "wave" as const, label: "こんにちは" },
        { mood: "think" as const, label: "じっくり考える" },
        { mood: "cheer" as const, label: "出荷を祝う" },
      ],
    },
    how: {
      eyebrow: "仕組み",
      title: "読む。作る。証明する。",
      description:
        "ひとつの制作ループ。AIには有限で安全な選択肢を。人には判断と最終決定を。",
      steps: [
        {
          key: "01",
          tag: "START",
          title: "体系を読む",
          body: "スクリーンショットや感覚ではなく、原則とルールIDから。",
          meta: "体系 · 原則",
          action: "体系を開く",
          href: "/canon",
        },
        {
          key: "02",
          tag: "BUILD",
          title: "実行可能な契約で作る",
          body: "セマンティックトークン、全状態の部品、目的起点の動き。",
          meta: "基礎 · コンポーネント · モーション",
          action: "部品を開く",
          href: "/components",
        },
        {
          key: "03",
          tag: "VERIFY",
          title: "選択を証明する",
          body: "主張を情報源へ辿る。ゲートを回す。システム状態を確認する。",
          meta: "レビュー · レポート · ステータス",
          action: "状態を開く",
          href: "/status",
        },
      ],
    },
    scale: {
      eyebrow: "根拠を伴う美意識",
      lead: "意見ではなく、",
      leadEmphasis: "計測値を。",
      description:
        "多くのデザイン集は美意識を売ります。AwesomeDSは、ローカルでもCIでもAIからでも検証できる証跡とともに美意識を届けます。",
      metrics: [
        { label: "件の標準ルール", sub: "すべて根拠に接続" },
        { label: "件の構造化情報源", sub: "鮮度を追跡" },
        { label: "個のライブ部品", sub: "全状態を契約化" },
        { label: "実装率", sub: "実装済みの標準ルール", suffix: "%" },
      ],
    },
    spectrum: {
      eyebrow: "CMYアイデンティティ",
      title: "3原色。設計されたスペクトラム。",
      body: "シアン・マゼンタ・イエロー——減法混色のロゴマーク。OKLCHスペクトラムが署名ストライプ。白い紙、濃いインク。暗いヒーローは使わない。",
      openBrand: "ブランド・バイブルを読む",
    },
    build: {
      eyebrow: "ライブコンポーネント",
      title: "ドキュメントそのものが動く。",
      description:
        "静止画ではなく、実際の @awesome-ds/react。ラベル、フォーカス、状態、操作契約をその場で。",
      actionCard: "操作契約",
      primary: "ブリーフを生成",
      secondary: "根拠を確認",
      loading: "情報源を確認中",
      fieldLabel: "デザインの意図",
      fieldHint: "意図を具体化すると、AIの安全な判断範囲を定められます。",
      fieldPlaceholder: "モバイル審査者向けの落ち着いた承認フロー",
      statusTitle: "根拠に接続済み",
      statusBody: "このパターンは標準ルールと一次情報を参照しています。",
      progress: "標準ルールの実装率",
      browse: "すべてのコンポーネントを見る",
    },
    motion: {
      eyebrow: "モーションライブラリ",
      title: "役割のある動き。",
      description:
        "目的別レシピを再生。使う場面、使わない場面、動きを減らす設定での代替を明示します。",
      replay: "動きを再生",
      replayed: "動きを再生しました",
      browse: "すべてのモーションを見る",
      demos: [
        {
          intent: "enter",
          label: "表示",
          description: "レイアウトをずらさず、新しい内容を示します。",
        },
        {
          intent: "feedback",
          label: "フィードバック",
          description: "明示的な操作に、短く応答します。",
        },
        {
          intent: "reveal",
          label: "段階表示",
          description: "一度だけ視線を導き、その後は静止します。",
        },
      ],
    },
    install: {
      eyebrow: "クイックスタート",
      title: "エージェントに指す。またはスキルを入れる。",
      tip: "まず design-system/INDEX.md を読み、必要なモジュールだけを開くよう指示してください。",
      code: "git clone https://github.com/Yu-aimaker/AwesomeDesignSystem.git\ncd AwesomeDesignSystem\n./install.sh",
      note: "5スキルを ~/.claude/skills にシンボリックリンク。リポジトリを置けば pull で更新されます。",
      skills: [
        { name: "/AwesomeDS", use: "美意識あるUIを構築・改善" },
        { name: "/MakeAwesomeDS", use: "ブランド固有のDSを生成" },
        { name: "/AwesomeHTML", use: "メモを単一HTMLに磨き上げ" },
        { name: "/AwesomeReview", use: "スロップとa11yを監査" },
        { name: "/AwesomeMotion", use: "目的起点のモーション設計" },
      ],
    },
    atlas: {
      eyebrow: "リファレンス・アトラス",
      title: "信頼の手がかりを、主張のそばに。",
      description:
        "提供元、証拠区分、最終確認、変化リスク、鮮度、関連ルール。ロゴ一覧は根拠になりません。",
      verified: "最終確認",
      freshness: "鮮度",
      linkedRules: "関連ルール",
      browse: "すべての情報源を見る",
    },
    closing: {
      eyebrow: "4つの入口",
      title: "扉を選んで、体系を持ち帰ろう。",
      quad: [
        { tag: "START", title: "体系を読む", href: "/canon" },
        { tag: "EXPLORE", title: "アトラスを辿る", href: "/references" },
        { tag: "BUILD", title: "部品を組む", href: "/components" },
        { tag: "VERIFY", title: "システム状態を見る", href: "/status" },
      ],
    },
  },
} as const;

export function getHomeContent(locale: Locale) {
  return content[locale];
}
