export const nav = [
  { href: "/", label: "Home", section: "explore" },
  { href: "/canon", label: "Canon", section: "explore" },
  { href: "/references", label: "Reference Atlas", section: "explore" },
  { href: "/foundations", label: "Foundations", section: "build" },
  { href: "/components", label: "Components", section: "build" },
  { href: "/motion", label: "Motion", section: "build" },
  { href: "/patterns", label: "Patterns", section: "build" },
  { href: "/playground", label: "Playground", section: "build" },
  { href: "/principles", label: "Principles", section: "practice" },
  { href: "/interaction", label: "Interaction", section: "practice" },
  { href: "/ai-design", label: "AI Design", section: "practice" },
  { href: "/brand", label: "Brand", section: "practice" },
  { href: "/review", label: "Review", section: "assure" },
  { href: "/status", label: "Status", section: "assure" },
] as const;
