export const nav = [
  { href: "/", label: "Home" },
  { href: "/canon", label: "Canon" },
  { href: "/principles", label: "Principles" },
  { href: "/foundations", label: "Foundations" },
  { href: "/brand", label: "Brand" },
  { href: "/review", label: "Review" },
  { href: "/interaction", label: "Interaction" },
  { href: "/patterns", label: "Patterns" },
  { href: "/ai-design", label: "AI Design" },
  { href: "/components", label: "Components" },
  { href: "/motion", label: "Motion" },
  { href: "/references", label: "Reference Atlas" },
  { href: "/playground", label: "Playground" },
  { href: "/status", label: "Status" },
] as const;
